
import mongoose, { Schema, Model } from "mongoose";

/**
 * StudyPlan Schema (The Brain)
 * Stores the "Contract" between the User and the Agent.
 */

export interface IStudyPlan {
    courseId: mongoose.Types.ObjectId;
    userId: mongoose.Types.ObjectId;

    // The "Goal" (e.g., "Get an A", "Pass the exam", "Learn for fun")
    goal: string;

    // Constraints
    examDate?: Date;
    hoursPerDay: number;
    availableDays: string[]; // ["Mon", "Wed", "Fri"]

    // Agent Memory (Why did I build this?)
    agentStrategy: string;

    // The "Phase" of the plan (e.g., "Foundational", "Exam Cram", "Maintenance")
    phase: string;

    // The Schedule (Generated by Agent)
    schedule: {
        date: Date;
        topicName: string;
        status: 'pending' | 'in-progress' | 'completed' | 'skipped';
        reasoning?: string; // Why this task today?
    }[];

    // Current Status
    status: 'active' | 'archived' | 'completed';
    progress: number; // 0-100
}

const StudyPlanSchema = new Schema<IStudyPlan>(
    {
        courseId: { type: Schema.Types.ObjectId, ref: "Course", required: true },
        userId: { type: Schema.Types.ObjectId, ref: "User", required: true },

        goal: { type: String, default: "General Mastery" },
        examDate: { type: Date },
        hoursPerDay: { type: Number, default: 1 },
        availableDays: { type: [String], default: ["Mon", "Tue", "Wed", "Thu", "Fri"] },

        agentStrategy: { type: String, default: "Standard pacing" },
        phase: { type: String, default: "Foundation" },

        schedule: [
            {
                date: { type: Date, required: true },
                topicName: { type: String, required: true },
                status: {
                    type: String,
                    enum: ['pending', 'in-progress', 'completed', 'skipped'],
                    default: 'pending'
                },
                reasoning: String
            }
        ],

        status: { type: String, enum: ['active', 'archived', 'completed'], default: 'active' },
        progress: { type: Number, default: 0 }
    },
    { timestamps: true }
);

// Prevent re-compilation in Next.js hot reload
export const StudyPlan: Model<IStudyPlan> = mongoose.models.StudyPlan || mongoose.model<IStudyPlan>("StudyPlan", StudyPlanSchema);
export default StudyPlan;
